# =========================
# Stage 1: Build Stage
FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npm run build

# =========================
# Stage 2: Run Stage – Nginx
# =========================
FROM nginx:alpine

# Non-root user
RUN adduser -D appuser
USER appuser

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
